### ISSUE TITLE
[Bug] The index of the formula for calculating weights is incorrect

### ISSUE THREAD

**Issue by 17373432** [rucy74/DAFA#1]
Thanks for your paper and code. There is a small issue in your code.
https://github.com/rucy74/DAFA/blob/4a7f87e76e7b85601aec80b4bc46d713f47ea3c7/utils.py#L51
In order to be consistent with formula (8) in your paper, the code should be changed to:
`weights_class[i] -= lamb * class_similarity[j, i] * class_similarity[i, i]`

**Comment by rucy74** [comment]
Thank you for letting me know! It seems there was a mistake during the process of simplifying the code. I'm sorry for the confusion. Although I did retrain the model and checked its performance after the simplification, I didn't notice the issue because the terms are either the similarity from class i to j or from class j to i, which didn't cause a significant difference in the results. In fact, the trend of performance improvement can still be observed in Table 9 of the paper

**Comment by 17373432** [comment]
Yes, this issue didn't affect the result much.
